//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monitoring_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Host
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Host()
        {
            this.State = false;
        }
    
        public System.Guid Host_ID { get; set; }
        public string IP { get; set; }
        public string DNS_Name { get; set; }
        public string Display_Name { get; set; }
        public bool State { get; set; }
        public System.DateTime Last_Appeal { get; set; }
    }
}
